// Textos originais para o modo Texto da Corrida.
export const TEXTS = [
  "A prática constante transforma precisão em velocidade. Mantenha os olhos na tela e deixe os dedos encontrarem as teclas com naturalidade.",
  "Digitar bem não significa apenas correr. Primeiro construa precisão, depois aumente o ritmo sem perder o controle das mãos.",
  "Tecnologia, estudo e trabalho ficam mais fluidos quando a digitação deixa de exigir esforço consciente e passa a acontecer por memória muscular.",
  "Pequenas sessões todos os dias costumam funcionar melhor do que um treino longo e cansativo. Regularidade é parte importante da evolução.",
  "Posicione os indicadores sobre F e J, relaxe os ombros e mantenha os punhos neutros enquanto percorre o teclado sem olhar para as mãos.",
  "O sol nasceu devagar sobre o rio. Na margem, algumas pessoas caminhavam enquanto a cidade começava a acordar. Era uma manhã tranquila, boa para organizar as ideias e planejar o dia.",
  "Antes de sair de casa, confira as chaves, a carteira e a garrafa de água. Um pequeno cuidado evita a pressa no caminho e deixa a rotina mais simples.",
  "Na feira do bairro, havia frutas, verduras e uma conversa em cada banca. O cheiro de café se misturava ao de pão quente, e ninguém parecia ter muita vontade de ir embora.",
  "A chuva chegou no fim da tarde e mudou o som da rua. As bicicletas pararam, as janelas se fecharam e o vento trouxe aquele cheiro de terra molhada.",
  "Uma boa conversa começa quando alguém decide escutar. Nem toda pergunta precisa de uma resposta imediata; às vezes, pensar por alguns segundos faz toda a diferença.",
  "O ônibus seguiu pela avenida enquanto as luzes se acendiam. Pela janela, a paisagem parecia uma sequência de pequenas histórias: uma loja fechando, um cachorro passeando e amigos se encontrando.",
  "Aprender algo novo exige paciência. No começo, até os passos mais simples parecem difíceis. Com prática e atenção, o que antes exigia esforço passa a fazer parte da rotina.",
  "Leia o enunciado com calma, identifique o que foi pedido e só então escolha a resposta. A pressa pode esconder detalhes importantes, mesmo quando você conhece bem o assunto.",
  "Uma mesa organizada ajuda a encontrar o material de estudo. Separe o caderno, escolha uma tarefa e deixe o celular longe por alguns minutos. Começar pequeno também é começar.",
  "Revisar não é apenas ler de novo. Tente explicar o assunto com suas próprias palavras, resolver uma questão e perceber onde ainda existe dúvida.",
  "Na biblioteca, o silêncio era interrompido apenas pelo som das páginas. Cada pessoa parecia viajar para um lugar diferente, mesmo estando sentada na mesma sala.",
  "O grupo dividiu o trabalho em pequenas partes. Cada integrante ficou responsável por uma tarefa e, antes da entrega, todos revisaram o resultado juntos. A colaboração deixou o projeto mais claro.",
  "Um programa pode falhar por um detalhe pequeno. Antes de mudar tudo, observe a mensagem de erro, repita o problema e teste uma hipótese de cada vez.",
  "A tecnologia faz parte de muitas tarefas do dia a dia. Ela ajuda a estudar, conversar e organizar informações, mas funciona melhor quando sabemos exatamente o que queremos fazer.",
  "Salvar uma cópia do arquivo antes de editar pode evitar retrabalho. Também vale escolher um nome claro, com uma descrição que permita reconhecer o conteúdo depois.",
  "A equipe lançou uma versão simples do aplicativo e ouviu os primeiros usuários. Algumas ideias foram mantidas, outras mudaram, e o projeto cresceu a partir de problemas reais.",
  "Uma tela bem organizada permite encontrar o que importa sem esforço. Títulos claros, botões visíveis e mensagens compreensíveis tornam a experiência mais agradável.",
  "O computador reiniciou, a conexão voltou e o arquivo continuou disponível. Mesmo assim, a equipe registrou o problema para entender o que aconteceu e evitar novas interrupções.",
  "No início do expediente, a equipe conferiu os pedidos e organizou as entregas. Um item estava sem identificação, então foi separado para revisão antes de seguir para a próxima etapa.",
  "Conferir uma informação leva menos tempo do que corrigir um erro depois. Compare os dados, observe as quantidades e pergunte quando algum detalhe não estiver claro.",
  "Um atendimento cuidadoso combina clareza e respeito. Ouça o pedido, explique as opções disponíveis e confirme se a pessoa entendeu qual será o próximo passo.",
  "A reunião terminou com três decisões: revisar o prazo, atualizar a lista de tarefas e avisar a equipe. Cada atividade ganhou um responsável, para que nada ficasse esquecido.",
  "A caixa chegou ao depósito com a etiqueta legível. Depois da conferência, os produtos foram organizados por categoria e registrados no sistema. Assim, ficou mais fácil localizar cada item.",
  "Às vezes, melhorar um processo significa retirar uma etapa desnecessária. Observe o caminho completo de uma tarefa e procure entender onde as pessoas perdem tempo ou precisam repetir o trabalho.",
  "A viagem começou antes do amanhecer. Na estrada, o céu mudou de cor aos poucos, e a primeira parada trouxe café, pão e uma boa conversa sobre os lugares que ainda seriam visitados.",
  "Na praça, crianças brincavam perto das árvores enquanto os adultos conversavam nos bancos. Um músico afinava o violão, preparando a trilha sonora daquele fim de tarde.",
  "O caminho até a cachoeira tinha pedras, curvas e pequenas pontes. O grupo seguiu sem pressa, observando a paisagem e parando sempre que alguém precisava descansar.",
  "O vento atravessou o quintal e espalhou folhas pelo chão. Perto do muro, uma planta que parecia esquecida mostrou sua primeira flor. A mudança era pequena, mas chamou a atenção de todos.",
  "Cozinhar também é uma forma de prestar atenção. Separe os ingredientes, leia a receita inteira e prove com cuidado. O resultado depende tanto das medidas quanto da paciência.",
  "Quem deixou o livro sobre a mesa? A pergunta começou uma pequena investigação em casa. Depois de procurar na sala inteira, descobriram que o dono estava lendo outro volume no quarto.",
  "A música começou baixinho e logo tomou conta da sala. Alguém marcou o ritmo com os pés, outra pessoa cantou o refrão e, por alguns minutos, até a louça da cozinha ficou para depois.",
  "Nem todo dia rende da mesma maneira. Faça o que for possível, respeite suas pausas e volte à tarefa com atenção. Uma rotina consistente também precisa de espaço para descansar.",
  "O desafio de hoje é manter um ritmo confortável do início ao fim. Observe os acentos, respeite os espaços e não deixe que um erro tire sua concentração das próximas palavras.",
  "Você prefere começar pelo mais fácil ou enfrentar logo a parte difícil? Não existe uma resposta única para todas as tarefas. Experimente caminhos diferentes e observe qual deles ajuda a manter o foco.",
  "O pequeno rato encontrou um teclado enorme no meio da oficina. Primeiro explorou a barra de espaço; depois, correu pelas letras como quem conhece uma pista secreta. Quando chegou ao fim, parou, respirou e decidiu tentar mais uma vez.",
  "No ateliê, a parede branca esperava a primeira linha. Com lápis, fita e algumas referências, o desenho ganhou forma aos poucos. Cada cor trouxe uma nova possibilidade para aquele canto da casa.",
  "O trem atravessou a ponte quando o sino da estação tocou. Na plataforma, uma senhora fechou o guarda-chuva e conferiu a passagem. Ainda havia tempo para comprar um café antes do embarque.",
  "A receita estava escrita no verso de um envelope. Entre manchas de farinha e pequenas anotações, aparecia o segredo da família: deixar a massa descansar e nunca abrir o forno antes da hora.",
  "O jardim da escola começou com três vasos e muita curiosidade. Os alunos anotavam as mudanças nas folhas, mediam os caules e discutiam qual seria a próxima semente a plantar.",
  "A trilha sonora mudou bem na curva da estrada. Ao longe, as montanhas pareciam desenhadas sobre o céu. Ninguém falou por alguns instantes; a paisagem já ocupava toda a conversa.",
  "Na oficina de bicicletas, cada ferramenta tinha seu lugar. O mecânico girou a roda, ajustou o freio e fez uma última inspeção. A bicicleta saiu pronta para novas aventuras pelo bairro.",
  "A exposição reunia fotografias de portas, janelas e fachadas antigas. Um visitante reconheceu a casa onde passou a infância. De repente, uma imagem simples virou uma história cheia de detalhes.",
  "A pequena livraria organizou uma troca de livros no sábado. Cada pessoa deixou um título e levou outro para casa. Dentro de um romance, alguém encontrou um bilhete desejando uma boa leitura.",
  "O céu escureceu durante o passeio de barco. O condutor observou as nuvens e decidiu voltar ao cais. O grupo terminou a tarde em uma varanda, ouvindo a chuva cair sobre o rio.",
  "Para montar o quebra-cabeça, eles começaram pelas bordas. Depois separaram as peças por cor e procuraram pequenos detalhes. A última peça estava escondida debaixo da própria caixa.",
  "No laboratório, a turma comparou duas amostras e registrou as diferenças. Um resultado inesperado gerou novas perguntas. A professora pediu que todos revisassem o procedimento antes de tirar conclusões.",
  "O campeonato do bairro reuniu equipes de várias ruas. Houve torcida, lanches e uma disputa equilibrada até o último minuto. Quando o jogo acabou, os adversários se juntaram para uma fotografia.",
  "A encomenda trazia um mapa, uma bússola e um caderno vazio. Parecia o começo de uma aventura. Na primeira página, uma frase convidava o leitor a observar melhor os caminhos que já conhecia.",
  "O rádio antigo voltou a funcionar depois de um pequeno reparo. Quando a primeira música tocou, a sala inteira ficou em silêncio. A melodia trouxe lembranças de festas, viagens e domingos em família.",
  "Uma ideia anotada no ônibus virou um projeto no fim de semana. O primeiro modelo tinha falhas, mas ajudou a entender o problema. Depois de alguns ajustes, já era possível mostrar a novidade aos amigos.",
  "Na cozinha comunitária, cada pessoa assumiu uma tarefa. Enquanto alguns cortavam os legumes, outros preparavam as mesas. O almoço ficou pronto no horário e ainda rendeu uma boa conversa entre vizinhos.",
  "O museu guardava objetos que pareciam comuns: uma mala, uma carta e um relógio. As legendas revelavam por que estavam ali. Cada peça contava um pedaço da vida de alguém que passou pela cidade.",
  "A ponte de madeira levava até uma pequena ilha. No caminho, era possível ouvir pássaros e observar os peixes perto da margem. O passeio terminou com um descanso à sombra de uma árvore.",
  "Quem organizou os arquivos por data encontrou o documento em poucos segundos. Quem salvou tudo com o mesmo nome precisou abrir várias pastas. Naquele dia, a equipe combinou um padrão mais simples.",
  "O pedido chegou com duas informações diferentes sobre o endereço. Antes de despachar a mercadoria, a atendente confirmou os dados com o cliente. A entrega seguiu para o destino certo naquela mesma tarde.",
  "A aula de fotografia começou sem câmeras. Primeiro, o grupo observou a luz, as sombras e as linhas da praça. Só depois cada participante escolheu um enquadramento para registrar a cena.",
  "O gato dormia ao lado do computador enquanto o projeto avançava. Ao ouvir o teclado parar, abriu um olho e espreguiçou. Parecia lembrar ao dono que também era hora de fazer uma pausa.",
  "Às 09:15, a equipe iniciou a conferência de 48 caixas. Cada volume recebeu uma etiqueta com a data e o destino. No fim da manhã, o relatório estava pronto para revisão.",
  "O convite dizia: traga uma história e algo para compartilhar. Apareceram bolos, fotografias, canções e lembranças engraçadas. A reunião terminou tarde, com a promessa de um novo encontro no mês seguinte."
]
