// Textos originais para o modo Texto da Corrida.
export const TEXTS = [
  "A prática constante transforma precisão em velocidade. Mantenha os olhos na tela e deixe os dedos encontrarem as teclas com naturalidade.",
  "Digitar bem não significa apenas correr. Primeiro construa precisão, depois aumente o ritmo sem perder o controle das mãos.",
  "Tecnologia, estudo e trabalho ficam mais fluidos quando a digitação deixa de exigir esforço consciente e passa a acontecer por memória muscular.",
  "Pequenas sessões todos os dias costumam funcionar melhor do que um treino longo e cansativo. Regularidade é parte importante da evolução.",
  "Posicione os indicadores sobre F e J, relaxe os ombros e mantenha os punhos neutros enquanto percorre o teclado sem olhar para as mãos.",
  "O sol nasceu devagar sobre o rio. Na margem, algumas pessoas caminhavam enquanto a cidade começava a acordar. Era uma manhã tranquila, boa para organizar as ideias e planejar o dia.",
  "Antes de sair de casa, confira as chaves, a carteira e a garrafa de água. Um pequeno cuidado evita a pressa no caminho e deixa a rotina mais simples.",
  "Na feira do bairro, havia frutas, verduras e uma conversa em cada banca. O cheiro de café se misturava ao de pão quente, e ninguém parecia ter muita vontade de ir embora.",
  "A chuva chegou no fim da tarde e mudou o som da rua. As bicicletas pararam, as janelas se fecharam e o vento trouxe aquele cheiro de terra molhada.",
  "Uma boa conversa começa quando alguém decide escutar. Nem toda pergunta precisa de uma resposta imediata; às vezes, pensar por alguns segundos faz toda a diferença.",
  "O ônibus seguiu pela avenida enquanto as luzes se acendiam. Pela janela, a paisagem parecia uma sequência de pequenas histórias: uma loja fechando, um cachorro passeando e amigos se encontrando.",
  "Aprender algo novo exige paciência. No começo, até os passos mais simples parecem difíceis. Com prática e atenção, o que antes exigia esforço passa a fazer parte da rotina.",
  "Leia o enunciado com calma, identifique o que foi pedido e só então escolha a resposta. A pressa pode esconder detalhes importantes, mesmo quando você conhece bem o assunto.",
  "Uma mesa organizada ajuda a encontrar o material de estudo. Separe o caderno, escolha uma tarefa e deixe o celular longe por alguns minutos. Começar pequeno também é começar.",
  "Revisar não é apenas ler de novo. Tente explicar o assunto com suas próprias palavras, resolver uma questão e perceber onde ainda existe dúvida.",
  "Na biblioteca, o silêncio era interrompido apenas pelo som das páginas. Cada pessoa parecia viajar para um lugar diferente, mesmo estando sentada na mesma sala.",
  "O grupo dividiu o trabalho em pequenas partes. Cada integrante ficou responsável por uma tarefa e, antes da entrega, todos revisaram o resultado juntos. A colaboração deixou o projeto mais claro.",
  "Um programa pode falhar por um detalhe pequeno. Antes de mudar tudo, observe a mensagem de erro, repita o problema e teste uma hipótese de cada vez.",
  "A tecnologia faz parte de muitas tarefas do dia a dia. Ela ajuda a estudar, conversar e organizar informações, mas funciona melhor quando sabemos exatamente o que queremos fazer.",
  "Salvar uma cópia do arquivo antes de editar pode evitar retrabalho. Também vale escolher um nome claro, com uma descrição que permita reconhecer o conteúdo depois.",
  "A equipe lançou uma versão simples do aplicativo e ouviu os primeiros usuários. Algumas ideias foram mantidas, outras mudaram, e o projeto cresceu a partir de problemas reais.",
  "Uma tela bem organizada permite encontrar o que importa sem esforço. Títulos claros, botões visíveis e mensagens compreensíveis tornam a experiência mais agradável.",
  "O computador reiniciou, a conexão voltou e o arquivo continuou disponível. Mesmo assim, a equipe registrou o problema para entender o que aconteceu e evitar novas interrupções.",
  "No início do expediente, a equipe conferiu os pedidos e organizou as entregas. Um item estava sem identificação, então foi separado para revisão antes de seguir para a próxima etapa.",
  "Conferir uma informação leva menos tempo do que corrigir um erro depois. Compare os dados, observe as quantidades e pergunte quando algum detalhe não estiver claro.",
  "Um atendimento cuidadoso combina clareza e respeito. Ouça o pedido, explique as opções disponíveis e confirme se a pessoa entendeu qual será o próximo passo.",
  "A reunião terminou com três decisões: revisar o prazo, atualizar a lista de tarefas e avisar a equipe. Cada atividade ganhou um responsável, para que nada ficasse esquecido.",
  "A caixa chegou ao depósito com a etiqueta legível. Depois da conferência, os produtos foram organizados por categoria e registrados no sistema. Assim, ficou mais fácil localizar cada item.",
  "Às vezes, melhorar um processo significa retirar uma etapa desnecessária. Observe o caminho completo de uma tarefa e procure entender onde as pessoas perdem tempo ou precisam repetir o trabalho.",
  "A viagem começou antes do amanhecer. Na estrada, o céu mudou de cor aos poucos, e a primeira parada trouxe café, pão e uma boa conversa sobre os lugares que ainda seriam visitados.",
  "Na praça, crianças brincavam perto das árvores enquanto os adultos conversavam nos bancos. Um músico afinava o violão, preparando a trilha sonora daquele fim de tarde.",
  "O caminho até a cachoeira tinha pedras, curvas e pequenas pontes. O grupo seguiu sem pressa, observando a paisagem e parando sempre que alguém precisava descansar.",
  "O vento atravessou o quintal e espalhou folhas pelo chão. Perto do muro, uma planta que parecia esquecida mostrou sua primeira flor. A mudança era pequena, mas chamou a atenção de todos.",
  "Cozinhar também é uma forma de prestar atenção. Separe os ingredientes, leia a receita inteira e prove com cuidado. O resultado depende tanto das medidas quanto da paciência.",
  "Quem deixou o livro sobre a mesa? A pergunta começou uma pequena investigação em casa. Depois de procurar na sala inteira, descobriram que o dono estava lendo outro volume no quarto.",
  "A música começou baixinho e logo tomou conta da sala. Alguém marcou o ritmo com os pés, outra pessoa cantou o refrão e, por alguns minutos, até a louça da cozinha ficou para depois.",
  "Nem todo dia rende da mesma maneira. Faça o que for possível, respeite suas pausas e volte à tarefa com atenção. Uma rotina consistente também precisa de espaço para descansar.",
  "O desafio de hoje é manter um ritmo confortável do início ao fim. Observe os acentos, respeite os espaços e não deixe que um erro tire sua concentração das próximas palavras.",
  "Você prefere começar pelo mais fácil ou enfrentar logo a parte difícil? Não existe uma resposta única para todas as tarefas. Experimente caminhos diferentes e observe qual deles ajuda a manter o foco.",
  "O pequeno rato encontrou um teclado enorme no meio da oficina. Primeiro explorou a barra de espaço; depois, correu pelas letras como quem conhece uma pista secreta. Quando chegou ao fim, parou, respirou e decidiu tentar mais uma vez."
]
